apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: frontend
      name: frontend
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/frontend:latest
              imagePullPolicy: Always
              name: frontend
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: gateway
      name: gateway
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
                  value: '{ enabled: false }'
                - name: SPRING_PROFILES_ACTIVE
                  value: dev
              image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/gateway:latest
              imagePullPolicy: Always
              name: gateway
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: inventory
      name: inventory
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/inventory:latest
              imagePullPolicy: Always
              name: inventory
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: orders
      name: orders
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/orders:latest
              imagePullPolicy: Always
              name: orders
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: customers
      name: customers
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/customers:latest
              imagePullPolicy: Always
              name: customers
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: "0"
                  memory: "0"
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
