apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: gateway
  name: gateway
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
              value: '{ enabled: false }'
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: default-route-openshift-image-registry.apps-crc.testing/enterprise-app/gateway:latest
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 8080
          resources:
            requests:
              ephemeral-storage: "0"
              memory: "0"
      restartPolicy: Always
      securityContext: {}
status: {}
