apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  zzz_deprecatedclustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: cfnodejsapp
      name: cfnodejsapp
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: BLUEMIX_REGION
                  value: region
                - name: VCAP_SERVICES
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_SERVICES
                      name: cfnodejsapp-vcapasenv
                - name: VCAP_APPLICATION
                  valueFrom:
                    secretKeyRef:
                      key: VCAP_APPLICATION
                      name: cfnodejsapp-vcapasenv
                - name: TEST_ENV
                  value: test-env-value
              image: 167641168138.dkr.ecr.us-east-1.amazonaws.com/ocp/cfnodejsapp:latest
              imagePullPolicy: Always
              name: cfnodejsapp
              ports:
                - containerPort: 8080
              resources:
                requests:
                  ephemeral-storage: 1024M
                  memory: 256M
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
