apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6ImlkIiwiYXBwbGljYXRpb25fbmFtZSI6ImNmbm9kZWpzYXBwIiwiYXBwbGljYXRpb25fdXJpcyI6WyJhcHAtdXJsIl0sImFwcGxpY2F0aW9uX3ZlcnNpb24iOiJhcHAtdmVyc2lvbiIsImNmX2FwaSI6Imh0dHBzOi8vYXBpLnJlZ2lvbi5jZi5jb20iLCJsaW1pdHMiOnsiZGlzayI6MTAyNCwiZmRzIjoxNjM4NCwibWVtIjoyNTZ9LCJuYW1lIjoiY2Zub2RlanNhcHAiLCJvcmdhbml6YXRpb25faWQiOiJvcmctaWQiLCJvcmdhbml6YXRpb25fbmFtZSI6Im9yZy1uYW1lIiwicHJvY2Vzc19pZCI6ImlkIiwicHJvY2Vzc190eXBlIjoid2ViIiwic3BhY2VfaWQiOiJzcGFjZS1pZCIsInNwYWNlX25hbWUiOiJkZXYiLCJ1cmlzIjpbImFwcC11cmwiXSwidXNlcnMiOm51bGwsInZlcnNpb24iOiJhcHAtdmVyc2lvbiJ9
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: cfnodejsapp-vcapasenv
type: Opaque
