
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    creationTimestamp: null
    name: myproject-clone-build-push
spec:
    params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
    tasks:
        - name: clone-1
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/frontend
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/frontend/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/frontend'
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-2
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-1
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-2
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/inventory
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/inventory/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/inventory'
          runAfter:
            - clone-2
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-3
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-2
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-3
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/gateway
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/gateway/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/gateway'
          runAfter:
            - clone-3
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-4
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-3
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-4
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/orders
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/orders/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/orders'
          runAfter:
            - clone-4
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
        - name: clone-5
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-4
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: myproject-shared-data
            - name: ssh-directory
              workspace: git-ssh-credentials
        - name: build-push-5
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/customers
            - name: DOCKERFILE
              value: '<TODO: fill this prefix starting from the root of the git repo>/customers/Dockerfile'
            - name: CONTEXT
              value: '<TODO: fill this prefix starting from the root of the git repo>/customers'
          runAfter:
            - clone-5
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: myproject-shared-data
            - name: dockerconfig
              workspace: registry-credentials
    workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: myproject-shared-data
        - description: This workspace provides the credentials (Docker config.json) for pushing images to the registry. See https://hub.tekton.dev/tekton/task/kaniko
          name: registry-credentials
        - description: This workspace provides the credentials (ssh private key) for cloning the git repo. See https://hub.tekton.dev/tekton/task/git-clone
          name: git-ssh-credentials

...
